name: Jekyll GitHub Pages

on:
  push:
    branches:
      - '**' # Run on all branches
  pull_request:
    branches:
      - main # Run on pull requests targeting the main branch

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2
        bundler-cache: true

    - name: Install dependencies
      run: bundle install

    - name: Debug Environment
      run: |
        echo "Ruby version: $(ruby -v)"
        echo "Bundler version: $(bundle -v)"
        echo "Installed gems:"
        bundle list

    - name: Debug Gemfile.lock
      run: cat Gemfile.lock

    - name: Build site
      run: bundle exec jekyll build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site
        publish_branch: gh-pages
